package me.anany.weikandian.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import me.anany.weikandian.db.entity.HomeTitleDB;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "HomeTitleDB".
*/
public class HomeTitleDBDao extends AbstractDao<HomeTitleDB, Long> {

    public static final String TABLENAME = "HomeTitleDB";

    /**
     * Properties of entity HomeTitleDB.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "ID");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Sort = new Property(2, String.class, "sort", false, "SORT");
        public final static Property Ut = new Property(3, String.class, "ut", false, "UT");
        public final static Property Pic = new Property(4, String.class, "pic", false, "PIC");
        public final static Property Cat_id = new Property(5, String.class, "cat_id", false, "CAT_ID");
        public final static Property Description = new Property(6, String.class, "description", false, "DESCRIPTION");
        public final static Property Is_new = new Property(7, String.class, "is_new", false, "IS_NEW");
        public final static Property Is_use = new Property(8, String.class, "is_use", false, "IS_USE");
    };

    private DaoSession daoSession;


    public HomeTitleDBDao(DaoConfig config) {
        super(config);
    }
    
    public HomeTitleDBDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"HomeTitleDB\" (" + //
                "\"ID\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"SORT\" TEXT," + // 2: sort
                "\"UT\" TEXT," + // 3: ut
                "\"PIC\" TEXT," + // 4: pic
                "\"CAT_ID\" TEXT," + // 5: cat_id
                "\"DESCRIPTION\" TEXT," + // 6: description
                "\"IS_NEW\" TEXT," + // 7: is_new
                "\"IS_USE\" TEXT);"); // 8: is_use
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_HomeTitleDB_ID ON HomeTitleDB" +
                " (\"ID\");");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"HomeTitleDB\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, HomeTitleDB entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String sort = entity.getSort();
        if (sort != null) {
            stmt.bindString(3, sort);
        }
 
        String ut = entity.getUt();
        if (ut != null) {
            stmt.bindString(4, ut);
        }
 
        String pic = entity.getPic();
        if (pic != null) {
            stmt.bindString(5, pic);
        }
 
        String cat_id = entity.getCat_id();
        if (cat_id != null) {
            stmt.bindString(6, cat_id);
        }
 
        String description = entity.getDescription();
        if (description != null) {
            stmt.bindString(7, description);
        }
 
        String is_new = entity.getIs_new();
        if (is_new != null) {
            stmt.bindString(8, is_new);
        }
 
        String is_use = entity.getIs_use();
        if (is_use != null) {
            stmt.bindString(9, is_use);
        }
    }

    @Override
    protected void attachEntity(HomeTitleDB entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public HomeTitleDB readEntity(Cursor cursor, int offset) {
        HomeTitleDB entity = new HomeTitleDB( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // sort
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // ut
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // pic
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // cat_id
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // description
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // is_new
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8) // is_use
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, HomeTitleDB entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setSort(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setUt(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setPic(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setCat_id(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setDescription(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setIs_new(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setIs_use(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(HomeTitleDB entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(HomeTitleDB entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
