package me.anany.weikandian.db.entity;

import me.anany.weikandian.db.dao.DaoSession;
import de.greenrobot.dao.DaoException;

import me.anany.weikandian.db.dao.HomeChannelDBDao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "HomeChannelDB".
 */
public class HomeChannelDB {

    private Long id;
    private String channle_id;
    private String is_use;
    private String name;
    private String pic;
    private String sname;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient HomeChannelDBDao myDao;


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public HomeChannelDB() {
    }

    public HomeChannelDB(Long id) {
        this.id = id;
    }

    public HomeChannelDB(Long id, String channle_id, String is_use, String name, String pic, String sname) {
        this.id = id;
        this.channle_id = channle_id;
        this.is_use = is_use;
        this.name = name;
        this.pic = pic;
        this.sname = sname;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getHomeChannelDBDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getChannle_id() {
        return channle_id;
    }

    public void setChannle_id(String channle_id) {
        this.channle_id = channle_id;
    }

    public String getIs_use() {
        return is_use;
    }

    public void setIs_use(String is_use) {
        this.is_use = is_use;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPic() {
        return pic;
    }

    public void setPic(String pic) {
        this.pic = pic;
    }

    public String getSname() {
        return sname;
    }

    public void setSname(String sname) {
        this.sname = sname;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
