package me.anany.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import me.anany.bean.HomeNewsDataItem;

import me.anany.dao.HomeNewsDataItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig homeNewsDataItemDaoConfig;

    private final HomeNewsDataItemDao homeNewsDataItemDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        homeNewsDataItemDaoConfig = daoConfigMap.get(HomeNewsDataItemDao.class).clone();
        homeNewsDataItemDaoConfig.initIdentityScope(type);

        homeNewsDataItemDao = new HomeNewsDataItemDao(homeNewsDataItemDaoConfig, this);

        registerDao(HomeNewsDataItem.class, homeNewsDataItemDao);
    }
    
    public void clear() {
        homeNewsDataItemDaoConfig.getIdentityScope().clear();
    }

    public HomeNewsDataItemDao getHomeNewsDataItemDao() {
        return homeNewsDataItemDao;
    }

}
