package me.anany.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import me.anany.bean.HomeItemDB;
import me.anany.bean.HomeTitleDB;
import me.anany.bean.HomeChannelDB;

import me.anany.dao.HomeItemDBDao;
import me.anany.dao.HomeTitleDBDao;
import me.anany.dao.HomeChannelDBDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig homeItemDBDaoConfig;
    private final DaoConfig homeTitleDBDaoConfig;
    private final DaoConfig homeChannelDBDaoConfig;

    private final HomeItemDBDao homeItemDBDao;
    private final HomeTitleDBDao homeTitleDBDao;
    private final HomeChannelDBDao homeChannelDBDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        homeItemDBDaoConfig = daoConfigMap.get(HomeItemDBDao.class).clone();
        homeItemDBDaoConfig.initIdentityScope(type);

        homeTitleDBDaoConfig = daoConfigMap.get(HomeTitleDBDao.class).clone();
        homeTitleDBDaoConfig.initIdentityScope(type);

        homeChannelDBDaoConfig = daoConfigMap.get(HomeChannelDBDao.class).clone();
        homeChannelDBDaoConfig.initIdentityScope(type);

        homeItemDBDao = new HomeItemDBDao(homeItemDBDaoConfig, this);
        homeTitleDBDao = new HomeTitleDBDao(homeTitleDBDaoConfig, this);
        homeChannelDBDao = new HomeChannelDBDao(homeChannelDBDaoConfig, this);

        registerDao(HomeItemDB.class, homeItemDBDao);
        registerDao(HomeTitleDB.class, homeTitleDBDao);
        registerDao(HomeChannelDB.class, homeChannelDBDao);
    }
    
    public void clear() {
        homeItemDBDaoConfig.getIdentityScope().clear();
        homeTitleDBDaoConfig.getIdentityScope().clear();
        homeChannelDBDaoConfig.getIdentityScope().clear();
    }

    public HomeItemDBDao getHomeItemDBDao() {
        return homeItemDBDao;
    }

    public HomeTitleDBDao getHomeTitleDBDao() {
        return homeTitleDBDao;
    }

    public HomeChannelDBDao getHomeChannelDBDao() {
        return homeChannelDBDao;
    }

}
