package me.anany.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import me.anany.bean.HomeNewsDataItem;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "HomeNewsDataItem".
*/
public class HomeNewsDataItemDao extends AbstractDao<HomeNewsDataItem, String> {

    public static final String TABLENAME = "HomeNewsDataItem";

    /**
     * Properties of entity HomeNewsDataItem.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", true, "ID");
        public final static Property Is_read = new Property(1, String.class, "is_read", false, "IS_READ");
        public final static Property Step = new Property(2, String.class, "step", false, "STEP");
        public final static Property Ct = new Property(3, String.class, "ct", false, "CT");
        public final static Property Catid = new Property(4, String.class, "catid", false, "CATID");
        public final static Property Thumb = new Property(5, String.class, "thumb", false, "THUMB");
        public final static Property Idx = new Property(6, String.class, "idx", false, "IDX");
        public final static Property Account_id = new Property(7, String.class, "account_id", false, "ACCOUNT_ID");
        public final static Property Isext = new Property(8, String.class, "isext", false, "ISEXT");
        public final static Property Title = new Property(9, String.class, "title", false, "TITLE");
        public final static Property Read_num = new Property(10, String.class, "read_num", false, "READ_NUM");
        public final static Property Like_num = new Property(11, String.class, "like_num", false, "LIKE_NUM");
        public final static Property Share_num = new Property(12, String.class, "share_num", false, "SHARE_NUM");
        public final static Property Wurl = new Property(13, String.class, "wurl", false, "WURL");
        public final static Property Video = new Property(14, String.class, "video", false, "VIDEO");
        public final static Property Image_type = new Property(15, String.class, "image_type", false, "IMAGE_TYPE");
        public final static Property Op_mark = new Property(16, String.class, "op_mark", false, "OP_MARK");
        public final static Property Op_mark_iurl = new Property(17, String.class, "op_mark_iurl", false, "OP_MARK_IURL");
        public final static Property Op_mark_icolor = new Property(18, String.class, "op_mark_icolor", false, "OP_MARK_ICOLOR");
        public final static Property Account_name = new Property(19, String.class, "account_name", false, "ACCOUNT_NAME");
        public final static Property Url = new Property(20, String.class, "url", false, "URL");
        public final static Property Is_cache = new Property(21, String.class, "is_cache", false, "IS_CACHE");
        public final static Property Article_type = new Property(22, String.class, "article_type", false, "ARTICLE_TYPE");
        public final static Property Behot_time = new Property(23, String.class, "behot_time", false, "BEHOT_TIME");
        public final static Property ExtraImg = new Property(24, String.class, "extraImg", false, "EXTRA_IMG");
    };


    public HomeNewsDataItemDao(DaoConfig config) {
        super(config);
    }
    
    public HomeNewsDataItemDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"HomeNewsDataItem\" (" + //
                "\"ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: id
                "\"IS_READ\" TEXT," + // 1: is_read
                "\"STEP\" TEXT," + // 2: step
                "\"CT\" TEXT," + // 3: ct
                "\"CATID\" TEXT," + // 4: catid
                "\"THUMB\" TEXT," + // 5: thumb
                "\"IDX\" TEXT," + // 6: idx
                "\"ACCOUNT_ID\" TEXT," + // 7: account_id
                "\"ISEXT\" TEXT," + // 8: isext
                "\"TITLE\" TEXT," + // 9: title
                "\"READ_NUM\" TEXT," + // 10: read_num
                "\"LIKE_NUM\" TEXT," + // 11: like_num
                "\"SHARE_NUM\" TEXT," + // 12: share_num
                "\"WURL\" TEXT," + // 13: wurl
                "\"VIDEO\" TEXT," + // 14: video
                "\"IMAGE_TYPE\" TEXT," + // 15: image_type
                "\"OP_MARK\" TEXT," + // 16: op_mark
                "\"OP_MARK_IURL\" TEXT," + // 17: op_mark_iurl
                "\"OP_MARK_ICOLOR\" TEXT," + // 18: op_mark_icolor
                "\"ACCOUNT_NAME\" TEXT," + // 19: account_name
                "\"URL\" TEXT," + // 20: url
                "\"IS_CACHE\" TEXT," + // 21: is_cache
                "\"ARTICLE_TYPE\" TEXT," + // 22: article_type
                "\"BEHOT_TIME\" TEXT," + // 23: behot_time
                "\"EXTRA_IMG\" TEXT);"); // 24: extraImg
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_HomeNewsDataItem_ID ON HomeNewsDataItem" +
                " (\"ID\");");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"HomeNewsDataItem\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, HomeNewsDataItem entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String is_read = entity.getIs_read();
        if (is_read != null) {
            stmt.bindString(2, is_read);
        }
 
        String step = entity.getStep();
        if (step != null) {
            stmt.bindString(3, step);
        }
 
        String ct = entity.getCt();
        if (ct != null) {
            stmt.bindString(4, ct);
        }
 
        String catid = entity.getCatid();
        if (catid != null) {
            stmt.bindString(5, catid);
        }
 
        String thumb = entity.getThumb();
        if (thumb != null) {
            stmt.bindString(6, thumb);
        }
 
        String idx = entity.getIdx();
        if (idx != null) {
            stmt.bindString(7, idx);
        }
 
        String account_id = entity.getAccount_id();
        if (account_id != null) {
            stmt.bindString(8, account_id);
        }
 
        String isext = entity.getIsext();
        if (isext != null) {
            stmt.bindString(9, isext);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(10, title);
        }
 
        String read_num = entity.getRead_num();
        if (read_num != null) {
            stmt.bindString(11, read_num);
        }
 
        String like_num = entity.getLike_num();
        if (like_num != null) {
            stmt.bindString(12, like_num);
        }
 
        String share_num = entity.getShare_num();
        if (share_num != null) {
            stmt.bindString(13, share_num);
        }
 
        String wurl = entity.getWurl();
        if (wurl != null) {
            stmt.bindString(14, wurl);
        }
 
        String video = entity.getVideo();
        if (video != null) {
            stmt.bindString(15, video);
        }
 
        String image_type = entity.getImage_type();
        if (image_type != null) {
            stmt.bindString(16, image_type);
        }
 
        String op_mark = entity.getOp_mark();
        if (op_mark != null) {
            stmt.bindString(17, op_mark);
        }
 
        String op_mark_iurl = entity.getOp_mark_iurl();
        if (op_mark_iurl != null) {
            stmt.bindString(18, op_mark_iurl);
        }
 
        String op_mark_icolor = entity.getOp_mark_icolor();
        if (op_mark_icolor != null) {
            stmt.bindString(19, op_mark_icolor);
        }
 
        String account_name = entity.getAccount_name();
        if (account_name != null) {
            stmt.bindString(20, account_name);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(21, url);
        }
 
        String is_cache = entity.getIs_cache();
        if (is_cache != null) {
            stmt.bindString(22, is_cache);
        }
 
        String article_type = entity.getArticle_type();
        if (article_type != null) {
            stmt.bindString(23, article_type);
        }
 
        String behot_time = entity.getBehot_time();
        if (behot_time != null) {
            stmt.bindString(24, behot_time);
        }
 
        String extraImg = entity.getExtraImg();
        if (extraImg != null) {
            stmt.bindString(25, extraImg);
        }
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public HomeNewsDataItem readEntity(Cursor cursor, int offset) {
        HomeNewsDataItem entity = new HomeNewsDataItem( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // is_read
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // step
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // ct
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // catid
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // thumb
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // idx
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // account_id
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // isext
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // title
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // read_num
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // like_num
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // share_num
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // wurl
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // video
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // image_type
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // op_mark
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // op_mark_iurl
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // op_mark_icolor
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // account_name
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // url
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // is_cache
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // article_type
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // behot_time
            cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24) // extraImg
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, HomeNewsDataItem entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setIs_read(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setStep(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCt(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setCatid(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setThumb(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setIdx(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setAccount_id(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setIsext(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setTitle(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setRead_num(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setLike_num(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setShare_num(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setWurl(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setVideo(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setImage_type(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setOp_mark(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setOp_mark_iurl(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setOp_mark_icolor(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setAccount_name(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setUrl(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setIs_cache(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setArticle_type(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setBehot_time(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setExtraImg(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(HomeNewsDataItem entity, long rowId) {
        return entity.getId();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(HomeNewsDataItem entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
