package me.anany.weikandian.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import me.anany.weikandian.entry.HomeTitle;

import me.anany.weikandian.db.HomeTitleDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig homeTitleDaoConfig;

    private final HomeTitleDao homeTitleDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        homeTitleDaoConfig = daoConfigMap.get(HomeTitleDao.class).clone();
        homeTitleDaoConfig.initIdentityScope(type);

        homeTitleDao = new HomeTitleDao(homeTitleDaoConfig, this);

        registerDao(HomeTitle.class, homeTitleDao);
    }
    
    public void clear() {
        homeTitleDaoConfig.clearIdentityScope();
    }

    public HomeTitleDao getHomeTitleDao() {
        return homeTitleDao;
    }

}
