package me.anany.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "HomeChannelDB".
 */
public class HomeChannelDB {

    private Long id;
    private String channle_id;
    private String is_use;
    private String name;
    private String pic;
    private String sname;

    public HomeChannelDB() {
    }

    public HomeChannelDB(Long id) {
        this.id = id;
    }

    public HomeChannelDB(Long id, String channle_id, String is_use, String name, String pic, String sname) {
        this.id = id;
        this.channle_id = channle_id;
        this.is_use = is_use;
        this.name = name;
        this.pic = pic;
        this.sname = sname;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getChannle_id() {
        return channle_id;
    }

    public void setChannle_id(String channle_id) {
        this.channle_id = channle_id;
    }

    public String getIs_use() {
        return is_use;
    }

    public void setIs_use(String is_use) {
        this.is_use = is_use;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPic() {
        return pic;
    }

    public void setPic(String pic) {
        this.pic = pic;
    }

    public String getSname() {
        return sname;
    }

    public void setSname(String sname) {
        this.sname = sname;
    }

}
