package me.anany.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "HomeTitleDB".
 */
public class HomeTitleDB {

    private Long id;
    private String name;
    private String sort;
    private String ut;
    private String pic;
    private String cat_id;
    private String description;
    private String is_new;
    private String is_use;

    public HomeTitleDB() {
    }

    public HomeTitleDB(Long id) {
        this.id = id;
    }

    public HomeTitleDB(Long id, String name, String sort, String ut, String pic, String cat_id, String description, String is_new, String is_use) {
        this.id = id;
        this.name = name;
        this.sort = sort;
        this.ut = ut;
        this.pic = pic;
        this.cat_id = cat_id;
        this.description = description;
        this.is_new = is_new;
        this.is_use = is_use;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSort() {
        return sort;
    }

    public void setSort(String sort) {
        this.sort = sort;
    }

    public String getUt() {
        return ut;
    }

    public void setUt(String ut) {
        this.ut = ut;
    }

    public String getPic() {
        return pic;
    }

    public void setPic(String pic) {
        this.pic = pic;
    }

    public String getCat_id() {
        return cat_id;
    }

    public void setCat_id(String cat_id) {
        this.cat_id = cat_id;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getIs_new() {
        return is_new;
    }

    public void setIs_new(String is_new) {
        this.is_new = is_new;
    }

    public String getIs_use() {
        return is_use;
    }

    public void setIs_use(String is_use) {
        this.is_use = is_use;
    }

}
